# Testing with B210

cu_cp:
  amf:
    addr: 10.53.1.2
    port: 38412
    bind_addr: 10.53.1.3
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "99999"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64
  srate: 23.04
  otw_format: sc12
  tx_gain: 80
  rx_gain: 40

cell_cfg:
  dl_arfcn: 628500                       # ARFCN of the downlink carrier (center frequency).
  band: 78                               # The NR band.
  channel_bandwidth_MHz: 20              # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                         # Subcarrier spacing in kHz used for data.
  plmn: "99999"                          # PLMN broadcasted by the gNB.
  tac: 7                                 # Tracking area code (needs to match the core configuration).
  pci: 1                                 # Physical cell ID.
  pdcch:
    common:
      ss0_index: 0
    dedicated:
      coreset1_rb_start: 0
      coreset1_l_crb: 48
      coreset1_duration: 2

      ss2_type: ue_dedicated
      ss2_n_candidates: [0, 0, 4, 0, 0]
      dci_format_0_1_and_1_1: true
  prach:
    prach_config_index: 1

log:
  filename: /logs/gnb.log                # Path of the log file.
  all_level: debug                       # Logging level applied to all layers. 

pcap:
  mac_enable: true
  mac_filename: /logs/gnb_mac.pcap

  rlc_enable: true
  rlc_filename: /logs/gnb_rlc.pcap

  ngap_enable: true
  ngap_filename: /logs/gnb_ngap.pcap

  n3_enable: true
  n3_filename: /logs/gnb_n3.pcap

metrics:
  autostart_stdout_metrics: true
  enable_json: true

remote_control:
  bind_addr: 0.0.0.0
  enabled: true
