# This is an Open5GS configuration file for a Standalone (SA) 5G Core Network setup.

db_uri: mongodb://${MONGODB_IP}/open5gs

logger:
  level: info
  file:
    path: /open5gs/logs/open5gs.log
  domain: amf,emm,gmm,udm,ausf,smf

test:
  serving:
    - plmn_id:
        mcc: 999
        mnc: 99

global:
  parameter:
    no_ipv6: true
    # no_nrf: true
    # no_scp: true
    no_sepp: true
    # no_amf: true
    # no_smf: true
    # no_upf: true
    # no_ausf: true
    # no_udm: true
    # no_pcf: true
    # no_nssf: true
    # no_bsf: true
    # no_udr: true
    no_mme: true
    no_sgwc: true
    no_sgwu: true
    no_pcrf: true
    no_hss: true

smf:
  sbi:
    server:
      - address: 127.0.0.4
        port: 7777
    client:
      nrf:
        - uri: http://127.0.0.10:7777
      scp:
        - uri: http://127.0.0.22:7777
  pfcp:
    server:
      - address: 127.0.0.4
    client:
      upf:
        - address: 127.0.0.7
  gtpc:
    server:
      - address: 127.0.0.4
  gtpu:
    server:
      - address: 127.0.0.4
  metrics:
    server:
      - address: 127.0.0.4
        port: 9090
  session:
    - subnet: ${UE_IP_RANGE}
      gateway: ${UE_GATEWAY_IP}
      # dnn: ${UE_APN}
  dns:
    - 8.8.8.8
    - 8.8.4.4
  mtu: 1400
  freeDiameter:
    identity: smf.localdomain
    realm: localdomain
    listen_on: 127.0.0.4
    no_fwd: true
    load_extension:
      - module: /open5gs/build/subprojects/freeDiameter/extensions/dbg_msg_dumps.fdx
        conf: 0x8888
      - module: /open5gs/build/subprojects/freeDiameter/extensions/dict_rfc5777.fdx
      - module: /open5gs/build/subprojects/freeDiameter/extensions/dict_mip6i.fdx
      - module: /open5gs/build/subprojects/freeDiameter/extensions/dict_nasreq.fdx
      - module: /open5gs/build/subprojects/freeDiameter/extensions/dict_nas_mipv6.fdx
      - module: /open5gs/build/subprojects/freeDiameter/extensions/dict_dcca.fdx
      - module: /open5gs/build/subprojects/freeDiameter/extensions/dict_dcca_3gpp/dict_dcca_3gpp.fdx
  security_indication:
    # Uncomment to enable UP integrity protection
    #integrity_protection_indication: preferred
    #confidentiality_protection_indication: preferred

amf:
  sbi:
    server:
      - address: 127.0.0.5
        port: 7777
    client:
      scp:
        - uri: http://127.0.0.22:7777
  ngap:
    server:
      - address: ${OPEN5GS_IP}
  metrics:
    server:
      - address: 127.0.0.5
        port: 9090
  guami:
    - plmn_id:
        mcc: 999
        mnc: 99
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: 999
        mnc: 99
      tac: 7
  plmn_support:
    - plmn_id:
        mcc: 999
        mnc: 99
      s_nssai:
        - sst: 1
          # dnn: [ ${UE_APN} ]
  security:
    integrity_order : [ NIA2, NIA1, NIA0 ]
    ciphering_order : [ NEA0, NEA1, NEA2 ]
  network_name:
    full: ${NETWORK_NAME_FULL}
    short: ${NETWORK_NAME_SHORT}
  amf_name: open5gs-amf0
  time:
    t3512:
      value: 540     # 9 minutes * 60 = 540 seconds


upf:
  pfcp:
    server:
      - address: 127.0.0.7
  metrics:
    server:
      - address: 127.0.0.7
        port: 9090
  gtpu:
    server:
      - address: ${OPEN5GS_IP}
        # advertise: ${UPF_ADVERTISE_IP}  # use only if you NAT across hosts
  session:
    - subnet: ${UE_IP_RANGE}
      gateway: ${UE_GATEWAY_IP}
      # dnn: ${UE_APN}

nrf:
  sbi:
    server:
      - address: 127.0.0.10
        port: 7777
  serving:  # 5G roaming requires PLMN in NRF
    - plmn_id:
        mcc: 999
        mnc: 99

scp:
  sbi:
    server:
      - address: 127.0.0.22
        port: 7777
    client:
      nrf:
        - uri: http://127.0.0.10:7777

ausf:
  sbi:
    server:
      - address: 127.0.0.11
        port: 7777
    client:
      scp:
        - uri: http://127.0.0.22:7777

udm:
  hnet:
    - id: 1
      scheme: 1
      key: /open5gs/build/configs/open5gs/hnet/curve25519-1.key
    - id: 2
      scheme: 2
      key: /open5gs/build/configs/open5gs/hnet/secp256r1-2.key
  sbi:
    server:
      - address: 127.0.0.12
        port: 7777
    client:
      nrf:
        - uri: http://127.0.0.10:7777
      scp:
        - uri: http://127.0.0.22:7777

pcf:
  sbi:
    server:
      - address: 127.0.0.13
        port: 7777
    client:
      nrf:
        - uri: http://127.0.0.10:7777
      scp:
        - uri: http://127.0.0.22:7777
  metrics:
    server:
      - address: 127.0.0.13
        port: 9090

nssf:
  sbi:
    server:
      - address: 127.0.0.14
        port: 7777
    client:
      scp:
        - uri: http://127.0.0.22:7777
      nsi:
        - uri: http://127.0.0.10:7777
          s_nssai:
            sst: 1
bsf:
  sbi:
    server:
      - address: 127.0.0.15
        port: 7777
    client:
      scp:
        - uri: http://127.0.0.22:7777

udr:
  sbi:
    server:
      - address: 127.0.0.20
        port: 7777
    client:
      scp:
        - uri: http://127.0.0.22:7777
